// Code generated by MockGen. DO NOT EDIT.
// Source: ./currency_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockExchangeRateRepo is a mock of ExchangeRateRepo interface.
type MockExchangeRateRepo struct {
	ctrl     *gomock.Controller
	recorder *MockExchangeRateRepoMockRecorder
}

// MockExchangeRateRepoMockRecorder is the mock recorder for MockExchangeRateRepo.
type MockExchangeRateRepoMockRecorder struct {
	mock *MockExchangeRateRepo
}

// NewMockExchangeRateRepo creates a new mock instance.
func NewMockExchangeRateRepo(ctrl *gomock.Controller) *MockExchangeRateRepo {
	mock := &MockExchangeRateRepo{ctrl: ctrl}
	mock.recorder = &MockExchangeRateRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExchangeRateRepo) EXPECT() *MockExchangeRateRepoMockRecorder {
	return m.recorder
}

// GetLatestRate mocks base method.
func (m *MockExchangeRateRepo) GetLatestRate() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestRate")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestRate indicates an expected call of GetLatestRate.
func (mr *MockExchangeRateRepoMockRecorder) GetLatestRate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestRate", reflect.TypeOf((*MockExchangeRateRepo)(nil).GetLatestRate))
}

// SaveRate mocks base method.
func (m *MockExchangeRateRepo) SaveRate(rate float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRate", rate)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRate indicates an expected call of SaveRate.
func (mr *MockExchangeRateRepoMockRecorder) SaveRate(rate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRate", reflect.TypeOf((*MockExchangeRateRepo)(nil).SaveRate), rate)
}

// MockRateProvider is a mock of RateProvider interface.
type MockRateProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRateProviderMockRecorder
}

// MockRateProviderMockRecorder is the mock recorder for MockRateProvider.
type MockRateProviderMockRecorder struct {
	mock *MockRateProvider
}

// NewMockRateProvider creates a new mock instance.
func NewMockRateProvider(ctrl *gomock.Controller) *MockRateProvider {
	mock := &MockRateProvider{ctrl: ctrl}
	mock.recorder = &MockRateProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRateProvider) EXPECT() *MockRateProviderMockRecorder {
	return m.recorder
}

// FetchRateFromAPI mocks base method.
func (m *MockRateProvider) FetchRateFromAPI() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRateFromAPI")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRateFromAPI indicates an expected call of FetchRateFromAPI.
func (mr *MockRateProviderMockRecorder) FetchRateFromAPI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRateFromAPI", reflect.TypeOf((*MockRateProvider)(nil).FetchRateFromAPI))
}
