services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: currency_notifier
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 2s
      timeout: 10s
      retries: 10
  wiremock:
    image: wiremock/wiremock:3.6.0
    volumes:
      - ./mocks/rate-provider:/home/wiremock
    ports:
      - "8282:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/__admin/health || exit 1" ]
      interval: 2s
      timeout: 10s
      retries: 10
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"